### ISSUE TITLE
Support for connect descriptors

### ISSUE THREAD

**Issue by razum90** [oracle/oracle-r2dbc#19]
Hi,

I can't find a way to set the connect descriptor in the URL like recommended here: https://docs.oracle.com/database/121/HABPT/config_fcf.htm#HABPT4967

Am I missing something or is this not supported?

**Comment by razum90** [comment]
Hi @Michael-A-McMahon and thanks for you answer,

All right. Do you think it would be possible to give the ability to set the descriptor via an Option on the ConnectionFactory too? As we are injecting the connection string (including the descriptor) through environment variables it would be easier for us to configure that way.

Ah ok, so UCP not supported. As we are using RAC it would be good to have that. Does UCP work with reactive extensions, or is that a blocker to integrate with it?

**Comment by Michael-A-McMahon** [comment]
You got me thinking about it, and now I've realized that you can set the descriptor as the value of ConnectionFactoryOptions.HOST.

Check out this code sample I just wrote:
https://github.com/oracle/oracle-r2dbc/blob/320d8ce3ecc1854107f57565756c7ba2efbe2950/sample/src/main/java/oracle/r2dbc/samples/DescriptorURL.java#L78

Would something like that work for your use case?

Concerning UCP: 
You are correct in that integration with UCP isn't possible until UCP supports truly asynchronous and non-blocking connection borrowing. The team is very much aware that bringing UCP's support for RAC over to R2DBC would be awesome, so we are looking into that.

**Comment by razum90** [comment]
Ah, perfect. This is what we needed, thank you.

Great, looking forward to UCP integration!

**Comment by mp911de** [comment]
Looking at the descriptor format (`(DESCRIPTION_LIST=(LOAD_BALANCE=off)(FAILOVER=on)…)`) it isn't a good fit for the R2DBC URL because its structure doesn't resemble what a URL would look like. Likely a driver-specific method to create a `ConnectionFactory` from a descriptor would make sense. 

Alternatively, trying to squeeze in the attributes into a URL could look like (as an idea):

`r2dbc:oracle:failover:loadbalance://prmy-scan:1521,stby-scan:1521?serviceName=oltpworkload&retryCount=3`

Since I'm not familiar with connect descriptors at all I have no idea how limiting this would be. `failover:loadbalance` would be parsed by R2DBC's URL parser as `protocol`, the host would contain `prmy-scan:1521,stby-scan:1521`.

**Comment by Michael-A-McMahon** [comment]
@mp911de I share the feeling that plugging in a descriptor where the host name should go is odd. A more objective reason not to do this might involve how a URL parser will process the descriptor; It's probably not safe to assume that a string of valid descriptor syntax will always be valid as a hostname.

A driver specific API might work.

I think most (perhaps all?) descriptor parameters can also be specified as connection properties to the underlying JDBC driver. This should allow for the alternative solution of setting failover, loadbalance, etc in the query section of the standard URL format.

I'll need to give this some more thought, but I'm also considering the idea of an extended option.

**Comment by Douglas-Surber** [comment]
How about putting the descriptor in the query portion of the URL?

Douglas

On Apr 1, 2021, at 9:57 PM, Michael McMahon ***@***.******@***.***>> wrote:



@mp911de<https://urldefense.com/v3/__https://github.com/mp911de__;!!GqivPVa7Brio!OT6rbC0L7Okb1jdFlVYI-9u3DQgVdA8AAYvLJMqdcQtsacmo39RMhjtSS-A2oBqZEIo$> I share the feeling that plugging in a descriptor where the host name should go is odd. A more objective reason not to do this might involve how a URL parser will process the descriptor; It's probably not safe to assume that a string of valid descriptor syntax will always be valid as a hostname.

A driver specific API might work.

I think most (perhaps all?) descriptor parameters can also be specified as connection properties to the underlying JDBC driver. This should allow for the alternative solution of setting failover, loadbalance, etc in the query section of the standard URL format.

I'll need to give this some more thought, but I'm also considering the idea of an extended option.

**Comment by Michael-A-McMahon** [comment]
I'm also thinking that moving the descriptor to the query section is the right way to go. To do so, we can define an extended Option that can appear in the query section. The option might be named "descriptor", in which case the URL would be written as:
`r2dbc:oracle://?descriptor=(DESCRIPTION=(ADDRESS=(HOST=example.com)(PORT=1521)(PROTOCOL=tcp))(CONNECT_DATA=(SERVICE_NAME=db.service.name)))`

The extended Option effectively offers a programatic API as well:
```java
ConnectionFactoryOptions.builder()
      .option(ConnectionFactoryOptions.DRIVER, "oracle")
      .option(Option.valueOf("descriptor"), "(DESCRIPTION=(ADDRESS=(HOST=example.com)(PORT=1521)(PROTOCOL=tcp))(CONNECT_DATA=(SERVICE_NAME=db.service.name)))")
...
```

The descriptor specifies values that may also appear in the standard URL format, such as host, port, and service name. We can't have one URL specifying different values in two places, so I think we'd need a rule that if the descriptor option is set, then the R2DBC URL must not otherwise specify these values. 
So a URL like this would result in an error:
`r2dbc:oracle://a.example.com:1522/a.db.service.name?descriptor==(DESCRIPTION=(ADDRESS=(HOST=b.example.com)(PORT=1521)(PROTOCOL=tcp))(CONNECT_DATA=(SERVICE_NAME=b.db.service.name)))`

**Comment by Michael-A-McMahon** [comment]
I'm wondering if we should name the option "oracle-descriptor", rather than just "descriptor". This avoids a potential name collision should the R2DBC SPI introduce a standard option named "descriptor" in the future.
It's the same reason why Oracle JDBC's has methods like "executeAsyncOracle" rather than just "executeAsync".

**Comment by Michael-A-McMahon** [comment]
Connect descriptors are now supported as a connection factory option.
