### ISSUE TITLE
Is Oracle support back ?

### ISSUE THREAD

**Issue by mehmetekici** [oracle/oracle-r2dbc#25]
Hi,
It has been unclear if there is Oracle database support for spring r2dbc. Is it active after Oracles odbc extention api?
When is the first lease planned ?

**Comment by Michael-A-McMahon** [comment]
I've seen others report that Spring R2DBC may need to implement a "dialect" for Oracle R2DBC:
https://groups.google.com/g/r2dbc/c/flbcmFu0ukk/m/uQnPaJEyBgAJ

So I don't think Spring R2DBC supports Oracle R2DBC at the moment. I can't speak to if or when Spring R2DBC would add that support since I'm not involved with that project.

**Comment by Michael-A-McMahon** [comment]
I don't know if there's an issue here that we can fix in the Oracle R2DBC code base. But I'll leave this open just in case I'm missing something.

**Comment by dpavanelli** [comment]
Support is available at least at springboot version 2.4.4. I'm using this driver with Webflux and Kotlin, and it's working fine. It's possible to configure the r2dbc connection with a simple url connection like:

```kotlin
    @Bean
    override fun connectionFactory(): ConnectionFactory {
        return ConnectionFactories.get("r2dbc:pool:oracle://$user:$password@$host:$port/$instance")
    }
```

Or using the ConnectionFactory builder like below:

```kotlin
   @Bean
   override fun connectionFactory(): ConnectionFactory {
        return ConnectionFactories.get(ConnectionFactoryOptions.builder()
                .option(ConnectionFactoryOptions.DRIVER, "pool")
                .option(ConnectionFactoryOptions.PROTOCOL, "oracle")
                .option(ConnectionFactoryOptions.HOST, dbHost)
                .option(ConnectionFactoryOptions.PORT, dbPort)
                .option(ConnectionFactoryOptions.DATABASE, dbInstance)
                .option(ConnectionFactoryOptions.USER, dbUser)
                .option(ConnectionFactoryOptions.PASSWORD, dbPassword)
                .option(Option.valueOf(OracleConnection.CONNECTION_PROPERTY_FAN_ENABLED), "false")
                .build());
   }
```

Both works as expected.

**Comment by dpavanelli** [comment]
https://docs.spring.io/spring-data/r2dbc/docs/current/api/org/springframework/data/r2dbc/dialect/OracleDialect.html

**Comment by mehmetekici** [comment]
Hi,
I wonder how stable the support for Oracle is?. Is there anyway to see the tests executed ? both on driver and the spring data support.
Thanks

**Comment by Michael-A-McMahon** [comment]
@mehmetekici I've been working on a github action that will execute our test suite: https://github.com/oracle/oracle-r2dbc/pull/2

When the action runs, it gets stuck. I believe the failure is due to the action executing in a single CPU environment, where Oracle R2DBC has a pool of just 1 thread. We use ForkJoinPool.commonPool(), which is sized according to the number of processors, so when there's one processor we get one thread. 

This failure has uncovered some defects where the underlying JDBC connection was accessed concurrently; This is not supported and can lead to threads indefinitely hanging as we see in the action runs.

I think I have all defects corrected now, as I was just able to run our full test suite locally with -Djava.util.concurrent.ForkJoinPool.common.parallelism=1. A new action run in now progress:
https://github.com/oracle/oracle-r2dbc/actions/runs/901324583

**Comment by Michael-A-McMahon** [comment]
@mehmetekici Finally managed to get the tests working in a github action, which you can see here: https://github.com/oracle/oracle-r2dbc/actions/runs/934202110

Outside of github actions, the Oracle R2DBC test suite can be viewed under src/test/java. To run the tests, create a config.properties file for your database under src/test/resources and run "mvn compile test". There's an example config.properties here: https://github.com/oracle/oracle-r2dbc/blob/main/src/test/resources/example-config.properties

We don't have integration tests with Spring, but we do test with the R2DBC TCK. The TCK should verify any behavior that Spring is expecting. However, the TCK is still being developed, so it may be missing some verifications.

**Comment by Michael-A-McMahon** [comment]
Closing this issue as Spring now claims support for v0.1.0 of Oracle R2DBC, and we have a github action that executes the R2DBC TCK.
Note that Spring does not currently support v0.2.0 of Oracle R2DBC, so Spring users should stick with v0.1.0 for now.
