### ISSUE TITLE
ERROR WHEN QUERY STRING IS LARGER THAN 4000 chars

### ISSUE THREAD

**Issue by kzmuhia** [oracle/oracle-r2dbc#34]
I get the error below 
Caused by: Error : 1401, Position : 14, Sql = ''  Error Msg = ORA-01401: inserted value too large for column

when  I have a large string in my where clause.

**Comment by Michael-A-McMahon** [comment]
@kzmuhia The database might raise ORA-01401 when the size of a bind value exceeds the size of a database column. I'll need some more details to determine if this is something that needs to be fixed in Oracle R2DBC. If you can describe how to recreate this failure, that would help.

**Comment by kzmuhia** [comment]
Hello Michael,

Thanks for your response

So I have the code below

build.gradle.kts

`   api("org.springframework.boot:spring-boot-starter-data-r2dbc")

    implementation("com.oracle.database.jdbc:ojdbc11-production:21.1.0.0")  
    
    implementation("com.oracle.database.r2dbc:oracle-r2dbc:0.1.0")  
    
    implementation("io.r2dbc:r2dbc-pool:0.8.2.RELEASE")  
    `


and below function which works when I concatenate the parameter onto the query as below

`suspend fun selectJwtTokenEntityByRawToken(token: String): JwtTokenEntity? {

        val query = "select *\n" +
        
                "from some_table\n" +
                
                "where RAW_TOKEN = '${token}'\n" +
                
                "order by ID"
                
        return template
        
            .databaseClient
            
            .sql(query)
            
           .bind("token", token)
           
            .map(convertRowToEntityMapping())
            
            .awaitSingleOrNull()
            
    }`


However when I run it as below by binding the parameter 

`suspend fun selectJwtTokenEntityByRawToken(token: String): JwtTokenEntity? {  

        val query = "select *\n" +  
        
                "from some_table\n" +  
                
                "where RAW_TOKEN = :token\n" +
                
                "order by ID"
                
        return template
        
            .databaseClient
            
            .sql(query)
            
            .bind("token", token)
            
            .map(convertRowToEntityMapping())
            
            .awaitSingleOrNull()
            
    }`

I get ORA-01401

the token string is a long string maybe upto 4k characters but shouldn't it fail for both?

**Comment by Michael-A-McMahon** [comment]
Thanks for the details, @kzmuhia.

I believe the cause of this failure is due to Oracle R2DBC 0.1.0 representing String bind values as NVARCHAR rather than VARCHAR. This behavior is no longer present in version 0.2.0. In 0.2.0, the driver represents String bind values as VARCHAR, and this seems to resolve the ORA-01401 failure.

However, Spring users should not update Oracle R2DBC to version 0.2.0 until Spring supports version 0.9.x of the R2DBC SPI. Last time I checked, Spring only supports 0.8.x.

To work around this with Oracle's 0.1.0 driver, the bind value can be converted to VARCHAR using Oracle's TO_CHAR function:
```
    val query = "select *\n" +  
    
            "from some_table\n" +  
            
            "where RAW_TOKEN = TO_CHAR(:token)\n" +
            
            "order by ID"
```
I wish there was a better solution, but that's the best I can think of at the moment.


_The remainder of this message is my analysis of this issue._
 

With the following code, I was able to recreate an ORA-01401 failure that occurs with a bind value but not with a single quote enclosed literal:
```java
import io.r2dbc.spi.Connection;
import io.r2dbc.spi.ConnectionFactories;
import io.r2dbc.spi.R2dbcException;
import io.r2dbc.spi.Result;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

public class StringBindTooLarge {
  public static void main(String[] args) {

    String token = new String(new char[4000]);

    Flux.usingWhen(ConnectionFactories.get(
      "r2dbc:oracle://test:test@localhost:1521/xepdb1")
      .create(),
      connection -> Flux.from(connection.createStatement(
        "DROP TABLE StringBindTooLarge")
        .execute())
        .flatMap(Result::getRowsUpdated)
        .onErrorResume(R2dbcException.class, r2dbcException ->
          r2dbcException.getErrorCode() == 942
            ? Mono.empty()
            : Mono.error(r2dbcException))
        .thenMany(connection.createStatement(
          "CREATE TABLE StringBindTooLarge (raw_token VARCHAR2(4000))")
          .execute())
        .flatMap(Result::getRowsUpdated)
        .thenMany(connection.createStatement(String.format(
          "INSERT INTO StringBindTooLarge VALUES ('%s')", token))
          .execute())
        .flatMap(Result::getRowsUpdated)
        .thenMany(connection.createStatement(
          "INSERT INTO StringBindTooLarge VALUES (:token)")
          .bind("token", token)
          .execute())
        .flatMap(Result::getRowsUpdated)
        .thenMany(connection.createStatement(String.format(
          "SELECT * FROM StringBindTooLarge WHERE raw_token = '%s'", token))
          .execute())
        .flatMap(result ->
          result.map((row, metadata) -> row.get(0)))
        .thenMany(connection.createStatement(
          "SELECT * FROM StringBindTooLarge WHERE raw_token = :token")
          .bind("token", token)
          .execute())
        .flatMap(result ->
          result.map((row, metadata) -> row.get(0))),
      Connection::close)
      .toStream()
      .forEach(System.out::println);
  }
}
```

Oracle's 0.1.0 implementation of Statement.bind(...) represents all String type values as NVARCHAR to the database. If I can assume that RAW_TOKEN is a VARCHAR type, this means that the condition in the where clause ends up comparing a VARCHAR to an NVARCHAR:
where RAW_TOKEN = :token

I believe that the VARCHAR to NVARCHAR comparison is what causes the ORA-01401 error. According to the SQL Language Reference book, the VARCHAR value of RAW_TOKEN would be converted into an NVARCHAR:

> Comparisons between CHAR and VARCHAR2 and between NCHAR and NVARCHAR2 types may entail different character sets. The default direction of conversion in such cases is from the database character set to the national character set.

https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/Data-Type-Comparison-Rules.html#GUID-98BE3A78-6E33-4181-B5CB-D96FD9DC1694

However, I can't find any documentation specifying that an ORA-01401 error would occur if a conversion to NVARCHAR results in a value that is larger then a column size. The documentation for this error code only states that it would be raised when inserting a value:

> ORA-01401: inserted value too large for column
> Cause: The value inserted was too large for the given column.
> 
> Action: Do not insert a value greater than what the column can hold.

https://docs.oracle.com/en/database/oracle/oracle-database/21/errmg/ORA-00900.html#GUID-D9EBDFFA-88C6-4185-BD2C-E1B959A97274

Although I can't find where the behavior we see is specified, I can observe the following:
1. When we use a single quote enclosed literal, the database performs a comparison between two VARCHARs, not between a VARCHAR and NVARCHAR, and the error does not occur.
2. If we convert the bind value to VARCHAR with the TO_CHAR function, the error does not occur.
3. When testing with Oracle's 0.2.0 implementation of Statement.bind(...), String bind values are no longer represented as NVARCHAR, and are represented as VARCHAR instead, and the error does not occur.

In all cases above, the error does not occur when comparing VARCHAR to VARCHAR. This suggests that it is the conversion from VARCHAR to NVARCHAR, brought about by comparing a VARCHAR to an NVARCHAR, which causes the ORA-01401.

**Comment by kzmuhia** [comment]
Thanks Michael I would be able to live with the workaround until 0.2.0 is supported
