### ISSUE TITLE
LOCK_WAIT_TIMEOUT

### ISSUE THREAD

**Issue by pradnyildhane** [oracle/oracle-r2dbc#61]
Getting error as java.long.NosSuchFieldError : LOCK_WAIT_TIMEOUT exception..

**Comment by zarate02** [comment]
me too 
i trans version to 0.2.0 and sucess

this problem occur to 0.3.0 and 0.4.0

**Comment by pradnyildhane** [comment]
Sadly for me the issue persists on 0.2.0 as well...

@Michael-A-McMahon  do you have any view on this why this might be.

**Comment by Michael-A-McMahon** [comment]
NoSuchFieldError might indicate that you have an older version of the r2dbc-spi jar. Older versions are incompatible with 0.2.0, 0.3.0, and 0.4.0 releases of Oracle R2DBC.

If you're using Spring, then you should stick with 0.1.0. Spring does not yet support the newer versions of Oracle R2DBC.

Otherwise, you need to make sure the version of the r2dbc-spi jar corresponds with the version number in the pom.xml from the release you are using.
0.2.0 depends on r2dbc-spi 0.9.0.M1: 
https://github.com/oracle/oracle-r2dbc/blob/662ceabf587eae8f5fb43bce4c2ccd4cb24bc080/pom.xml#L69
0.3.0 depends on r2dbc-spi 0.9.0.M2:
https://github.com/oracle/oracle-r2dbc/blob/57e57af78e3f703b36a9cffe358c09c947760000/pom.xml#L69
0.4.0 depends on r2dbc-spi 0.9.0.RELEASE:
https://github.com/oracle/oracle-r2dbc/blob/260a09a484735863699ac4fdb1ab0b452ec514ee/pom.xml#L69

Maven should be downloading the right version already, but it might also be downloading an older version if you have another library (like Spring) that depends on the older version.

**Comment by Michael-A-McMahon** [comment]
I hope I was able to help. I'll be closing this issue now, but please let know if there's more to discuss.
